#!/usr/bin/env bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

nix-shell --add-root $DIR/dist-ghcjs/gc-roots/gc-root --indirect $DIR/shell-ghcjs.nix --run "cabal --project-file=$DIR/cabal-ghcjs.project --builddir=dist-ghcjs --ghcjs $(printf "%q " "$@")"
